# Generated by Django 6.1.1 on 2026-09-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bekend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.IntegerField(null=True),
        ),
    ]
