# Generated by Django 6.1.1 on 2026-09-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bekend', '0002_product_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rasm',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
