# Generated by Django 6.1.1 on 2026-09-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bekend', '0003_product_rasm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rate',
            field=models.FloatField(null=True),
        ),
    ]
